[colors]
base = #1e1e2e
mantle = #181825
crust = #11111b
text = #cdd6f4
subtext0 = #a6adc8
subtext1 = #bac2de
surface0 = #313244
surface1 = #45475a
surface2 = #585b70
overlay0 = #6c7086
overlay1 = #7f849c
overlay2 = #9399b2
blue = #89b4fa
lavender = #b4befe
sapphire = #74c7ec
sky = #89dceb
teal = #94e2d5
green = #a6e3a1
yellow = #f9e2af
peach = #fab387
maroon = #eba0ac
red = #f38ba8
mauve = #cba6f7
pink = #f5c2e7
flamingo = #f2cdcd
rosewater = #f5e0dc
transparent = #FF00000

;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = ${colors.base}
background-alt = ${colors.blue}
foreground = ${colors.text}
primary = ${colors.mauve}
secondary = ${colors.mantle}
alert = ${colors.red}
disabled = ${colors.subtext1}

[bar/toph]
monitor = ${env:MONITOR:}
width = 100%
height = 28pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

bottom = true

line-size = 6pt

#border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.flamingo}

font-0 = MesloLGS Nerd Font Mono:size=12;6
font-1 = MesloLGS Nerd Font Mono:size=15;6
font-2 = MesloLGS Nerd Font Mono:size=18;6
font-3 = MesloLGS Nerd Font Mono:size=22;6



modules-left = xworkspaces xwindow
modules-center = date
modules-right = pulseaudio battery-internal battery memory cpu wlan bluetooth

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.mauve}
label-active-foreground = ${colors.crust}
label-active-underline= ${colors.lauve}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:25:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}


[module/pulseaudio]
type = internal/pulseaudio

format-volume = %{T3}<ramp-volume>%{T-} <label-volume>
label-volume = %percentage%%

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = ${colors.primary}

label-muted = %{T3}%{T-} muted
label-muted-foreground = ${colors.disabled}



[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/battery]
type = internal/battery
format-prefix = "BAT "
format-prefix-foreground = ${colors.primary}
full-at = 99
format-charging = <animation-charging> <label-charging>

animation-charging-0 = %{T3}%{T-}
animation-charging-1 = %{T3}%{T-}
animation-charging-2 = %{T3}%{T-}
animation-charging-3 = %{T3}%{T-}
animation-charging-4 = %{T3}%{T-}

; Framerate in milliseconds
animation-charging-framerate = 750
animation-charging-foreground = ${colors.peach}
format-discharging = <ramp-capacity> <label-discharging>

ramp-capacity-0 = %{T3}%{T-}
ramp-capacity-1 = %{T3}%{T-}
ramp-capacity-2 = %{T3}%{T-}
ramp-capacity-3 = %{T3}%{T-}
ramp-capacity-4 = %{T3}%{T-}

low-at = 5
battery = BAT1
adapter = ACAD
poll-interval = 5

[module/battery-internal]
type = internal/battery

format-prefix = "BAT "
format-prefix-foreground = ${colors.primary}

full-at = 99
low-at = 5

battery = BAT0
adapter = ACAD
poll-interval = 5

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>

animation-charging-0 = %{T3}%{T-}
animation-charging-1 = %{T3}%{T-}
animation-charging-2 = %{T3}%{T-}
animation-charging-3 = %{T3}%{T-}
animation-charging-4 = %{T3}%{T-}
animation-charging-framerate = 750
animation-charging-foreground = ${colors.peach}

ramp-capacity-0 = %{T3}%{T-}
ramp-capacity-1 = %{T3}%{T-}
ramp-capacity-2 = %{T3}%{T-}
ramp-capacity-3 = %{T3}%{T-}
ramp-capacity-4 = %{T3}%{T-}


[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected




[module/wlan]
type = internal/network
interface = wlp3s0
interval = 5

format-connected = <label-connected>
label-connected = %{A1:kitty -e nmtui:}%{T2}%{T-} %essid%%{A}
label-connected-foreground = ${colors.primary}

format-disconnected = <label-disconnected>
label-disconnected = %{A1:kitty -e nmtui:}%{T2}%{T-} offline%{A}
label-disconnected-foreground = ${colors.disabled}




[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %I:%M %p
date-alt = %A, %d %B %I:%M %p

label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/bluetooth]
type = custom/text
content = 
content-foreground = ${colors.primary}
click-left = kitty -e bluetoothctl

[module/lock]
type = custom/text
content = 
content-foreground = ${colors.primary}
click-left = ~/.config/rofi/powermenu.sh




; vim:ft=dosini
