[ids]
0001:0001
0000:0000:2e47d5d9

[main]
capslock = layer(numbers)
rightalt = leftcontrol


[numbers]
pagedown = brightnessdown
pageup = brightnessup

backspace = playpause
home = previoussong
end = nextsong

; = oneshot(shift)
w = 1
e = 2
r = 3
t = 4
s = 5
d = 6
f = 7
g = 8
c = 9
v = 0
n = -
m = =
p = \
[ = `
b = toggle(shift)
x = oneshot(control)

i = backspace
o = delete
space = escape

h = left
j = down
k = up
l = right

y = home
u = end
